# Generated by Django 3.2.8 on 2021-10-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorize', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('music_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorize.musicschool')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('composition_count', models.IntegerField()),
                ('min_difficulty', models.IntegerField()),
                ('max_difficulty', models.IntegerField()),
                ('music_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorize.musicschool')),
            ],
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('mark', models.IntegerField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.composition')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compositions', models.ManyToManyField(to='api.Composition')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.concert')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instrument'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorize.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorize.teacher'),
        ),
        migrations.CreateModel(
            name='CompositionRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100)),
                ('sheme', models.JSONField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.composition')),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instrument'),
        ),
    ]
