# Generated by Django 3.2.8 on 2021-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='compositions',
            field=models.ManyToManyField(null=True, to='api.Composition'),
        ),
    ]
