# Generated by Django 3.2.8 on 2021-11-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_program_compositions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='compositions',
            field=models.ManyToManyField(blank=True, null=True, to='api.Composition'),
        ),
    ]
