# Generated by Django 3.2.8 on 2022-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_feedback_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetition',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
