# Generated by Django 3.2.8 on 2022-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_repetition_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetition',
            name='mark',
            field=models.FloatField(),
        ),
    ]
