# Generated by Django 3.2.8 on 2021-11-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0003_auto_20211128_1912'),
        ('api', '0004_auto_20211128_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='music_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorize.musicschool'),
        ),
    ]
